version: 0.2

phases:
  build:
    commands:
      - mvn clean package
      - sam package --template-file sam-template.yml --s3-bucket $S3_BUCKET --output-template-file out-sam-template.yml

artifacts:
  files:
    - out-sam-template.yml

cache:
  paths:
    - '/root/.m2/**/*'