AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: AWS lambda for auto-formation purpose.
Resources:
  hellojava:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/my-app-autonome-0.0.1-SNAPSHOT.jar
      Handler: example.HelloHandler
      Runtime: java11
      Description: Java function
      FunctionName: my-app-autonome
      MemorySize: 128
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
      AutoPublishAlias: live
      DeploymentPreference:
#        Type: Canary10Percent5Minutes
        Type: AllAtOnce
        Hooks:
#           Validation Lambda functions that are run before & after traffic shifting
          PreTraffic: !Ref PreTrafficHook
#          PostTraffic: arn:aws:lambda:eu-west-3:870103585828:function:CodeDeployHook_posthook

  PreTrafficHook:
    Type: AWS::Serverless::Function
    Properties:
      DeploymentPreference:
        Enabled: False
      CodeUri: target/my-app-autonome-0.0.1-SNAPSHOT.jar
      Handler: hooks.PreTrafficHook
      Runtime: java11
      Description: Java function
      FunctionName: CodeDeployHook_prehook
      MemorySize: 512
      Environment:
        Variables:
          NewLambdaVersion: !Ref hellojava.Version
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AdministratorAccess
        - AWSLambdaFullAccess
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "codedeploy:PutLifecycleEventHookExecutionStatus"
              Resource: "*"