Resources:

  CodeCommitRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryDescription: repo pour my-app-autonome
      RepositoryName: my-app-autonome

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: my-app-autonome
      Description: A build project for my-app-autonome
      ServiceRole: arn:aws:iam::870103585828:role/codebuild-my-build-project-role
      Artifacts:
        Type: S3
        Location: joseph-codedeploy
        Packaging: ZIP
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/java:openjdk-11
        EnvironmentVariables:
          - Name: S3_BUCKET
            Type: PLAINTEXT
            Value: joseph-codedeploy
      Source:
        Location: https://git-codecommit.eu-west-3.amazonaws.com/v1/repos/my-app-autonome
        Type: CODECOMMIT
      TimeoutInMinutes: 5

