Parameters:
  ApplicationName:
    Default: ''
    Type: String
    Description: Application Name
  SourceCodeBucketName:
    Default: 'joseph-codedeploy'
    Type: String
    Description: CodeCommit init source bucket
  SourceCodeBucketKey:
    Default: 'my-app-autonome-starter.zip'
    Type: String
    Description: CodeCommit init source item key
  GithubRepo:
    Default: 'mbimbij/aws-serverless-cicd-autonomie'
    Type: String
    Description: Github source code repository

Resources:
  S3Bucket:
    DeletionPolicy: Delete
    Type: 'AWS::S3::Bucket'
    Description: Creating Amazon S3 bucket for AWS CodePipeline artifacts
    Properties:
      BucketName: !Join
        - '-'
        - - aws
          - !Ref 'AWS::Region'
          - !Ref 'AWS::AccountId'
          - !Ref ApplicationName
          - pipelinebucket
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Value: !Join
            - '-'
            - - !Ref ApplicationName
              - S3Bucket
          Key: Name

  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Join
        - '-'
        - - !Ref ApplicationName
          - build-project
      Description: A build project for my-app-autonome
      ServiceRole: !Ref BuildProjectRole
      Artifacts:
        Type: CODEPIPELINE
        Packaging: ZIP
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        EnvironmentVariables:
          - Name: S3_BUCKET
            Type: PLAINTEXT
            Value: !Ref S3Bucket
      TimeoutInMinutes: 5
      Cache:
        Type: S3
        Location: !Sub '${S3Bucket}/maven-cache'
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            build:
              commands:
                - mvn clean package
                - sam package --template-file sam-template.yml --s3-bucket $S3_BUCKET --output-template-file out-sam-template.yml
          artifacts:
            files:
              - out-sam-template.yml
          cache:
            paths:
              - '/root/.m2/**/*'

  GithubConnection:
    Type: AWS::CodeStarConnections::Connection
    Properties:
      ConnectionName: !Join
        - '-'
        - - !Ref ApplicationName
          - connection
      ProviderType: GitHub

  Pipeline:
    Description: Creating a deployment pipeline for your project in AWS CodePipeline
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      RoleArn: !GetAtt
        - PipelineRole
        - Arn
      ArtifactStore:
        Type: S3
        Location: !Ref S3Bucket
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeStarSourceConnection
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                ConnectionArn: !Ref GithubConnection
                FullRepositoryId: !Ref GithubRepo
                BranchName: "main"
                OutputArtifactFormat: "CODE_ZIP"
        - Name: Build
          Actions:
            - Name: Build
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName:
                  Ref: BuildProject
        - Name: Deploy
          Actions:
            - Name: Deploy
              RunOrder: 1
              InputArtifacts:
                - Name: BuildOutput
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !GetAtt
                  - CloudFormationRole
                  - Arn
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND,CAPABILITY_IAM
                TemplatePath: !Sub 'BuildOutput::out-sam-template.yml'
                StackName: !Join
                  - '-'
                  - - !Ref ApplicationName
                    - 'sam-application-stack'

  BuildProjectRole:
    Type: 'AWS::IAM::Role'
    Description: IAM role for build resource
    Properties:
      RoleName: !Join
        - '-'
        - - !Ref ApplicationName
          - build-role
      Path: /
      Policies:
        - PolicyName: !Join
            - '-'
            - - !Ref ApplicationName
              - build-policy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: "*"
                Resource:
                  - !Sub 'arn:${AWS::Partition}:s3:::${S3Bucket}'
                  - !Sub 'arn:${AWS::Partition}:s3:::${S3Bucket}/*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
      AssumeRolePolicyDocument:
        Statement:
          - Action: "sts:AssumeRole"
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com

  PipelineRole:
    Type: 'AWS::IAM::Role'
    Description: IAM role for pipeline resources
    Properties:
      RoleName: !Join
        - '-'
        - - !Ref ApplicationName
          - pipeline-role
      Path: /
      Policies:
        - PolicyName: !Join
            - '-'
            - - !Ref ApplicationName
              - policy
          PolicyDocument:
            Statement:
              - Action:
                  - '*'
                Resource:
                  - !Sub 'arn:${AWS::Partition}:s3:::${S3Bucket}'
                  - !Sub 'arn:${AWS::Partition}:s3:::${S3Bucket}/*'
                Effect: Allow
              - Action:
                  - 'cloudtrail:CreateTrail'
                  - 'cloudtrail:StartLogging'
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:DescribeLogGroups'
                  - 'logs:PutLogEvents'
                Resource: '*'
                Effect: Allow
              - Action:
                  - 'kms:GenerateDataKey*'
                  - 'kms:Encrypt'
                  - 'kms:Decrypt'
                Resource: '*'
                Effect: Allow
              - Action:
                - 'codestar-connections:UseConnection'
                Resource: '*'
                Effect: Allow
              - Action:
                - 'codebuild:StartBuild'
                Resource: '*'
                Effect: Allow
              - Action:
                - 'iam:PassRole'
                Resource:
                - !GetAtt
                  - CloudFormationRole
                  - Arn
                Effect: Allow
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
        - arn:aws:iam::aws:policy/IAMFullAccess
        - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess

  CloudFormationRole:
    Type: 'AWS::IAM::Role'
    Description: IAM role for cloudformation deploy resource
    Properties:
      RoleName: !Join
        - '-'
        - - !Ref ApplicationName
          - cloudformation-role
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
        - arn:aws:iam::aws:policy/IAMFullAccess
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AWSCodeDeployFullAccess
